version: "3.4"

networks:
  mongodb-network:
  godbox-network:
  tradistonks-api:
    name: tradistonks-api

services:
  tradistonks-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/:/usr/src/app/src/
    networks:
      - mongodb-network
      - godbox-network
      - tradistonks-api
    ports:
      - 3000:3000
    env_file: .env
    environment:
      MONGODB_URL: ${MONGODB_URL}
      GODBOX_URL: ${GODBOX_URL}
      JWT_SECRET: ${JWT_SECRET}
      API_EXTERNAL_HOST: ${API_EXTERNAL_HOST}
      API_INTERNAL_HOST: ${API_INTERNAL_HOST}

  mongodb:
    image: mongo:latest
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    networks:
      - mongodb-network
    ports:
      - 27018:27017

  godbox:
    image: quantumsheep/godbox
    privileged: true
    networks:
      - godbox-network
